# Generated by Django 5.0.3 on 2024-04-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_comment_enrollment_grade_lesson_module_option_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='AnswerOptions',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Grade',
            new_name='Grades',
        ),
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lessons',
        ),
        migrations.RenameModel(
            old_name='Module',
            new_name='Modules',
        ),
        migrations.RenameModel(
            old_name='PostedComment',
            new_name='PostedComments',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='Roles',
        ),
        migrations.AlterModelTable(
            name='answeroptions',
            table='answeroptions',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='grades',
            table='grades',
        ),
        migrations.AlterModelTable(
            name='lessons',
            table='lessons',
        ),
        migrations.AlterModelTable(
            name='modules',
            table='modules',
        ),
        migrations.AlterModelTable(
            name='postedcomments',
            table='postedcomments',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
    ]
